certmanager:
  email: mariuszrajczakowski@gmail.com

cluster_issuer:
  name: letsencrypt-prod
  server: https://acme-v02.api.letsencrypt.org/directory

ingress:
  name: kube-ts-ingress
  api:
    host: api.mariuszrajczakowski.me
    serviceName: kube-ts-server
    servicePort: 80
  client:
    host: client.mariuszrajczakowski.me
    serviceName: kube-ts-client
    servicePort: 80

