apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cluster_issuer.name }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.ingress.name }}
    # Email address used for ACME registration
    email: {{ .Values.certmanager.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.ingress.name }}
    # Enable the HTTP-01 challenge provider
    http01: {}