apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.name }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.api.host }}
    - {{ .Values.ingress.client.host }}
    secretName: letsencrypt-prod
  rules:
  - host: {{ .Values.ingress.api.host }}
    http: 
      paths:
      - backend:
          serviceName: {{ .Values.ingress.api.serviceName }}
          servicePort: {{ .Values.ingress.api.servicePort }}
  - host: {{ .Values.ingress.client.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.ingress.client.serviceName }}
          servicePort: {{ .Values.ingress.client.servicePort }}

          