apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-ts-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.mariuszrajczakowski.me
    secretName: letsencrypt-prod
  rules:
  - host: api.mariuszrajczakowski.me
    http:
      paths:
      - backend:
          serviceName: kube-ts-server
          servicePort: 80

          